name: Build Docker image may be

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Login to docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build for dev
        run: docker build -t asheer/flying-fibo-test -f ./client/Dockerfile.dev  ./client
      
      - name: Run npm test 
        run: docker run  -e CI=true asheer/flying-fibo-test npm test -- --coverage
       
      - name: Build for Prod
        run: |
         docker build -t asheer/flyingfibo-client  ./client
         docker build -t asheer/flyingfibo-worker  ./worker
         docker build -t asheer/flyingfibo-nginx   ./nginx
         docker build -t asheer/flyingfibo-server  ./server

      - name: Pushing to DH   
        run: |
         docker push asheer/flyingfibo-server
         docker push asheer/flyingfibo-worker 
         docker push asheer/flyingfibo-nginx 
         docker push asheer/flyingfibo-server

      - name: Deploy 2 EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Dockereact-env
          existing_bucket_name: ${{ secrets.ASS3_BUCKET }}
          region: us-west-2
          version_label: ${{ github.sha }}






