name: Build Docker image may be

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t asheer/flying-fibo-test -f ./client/Dockerfile.dev  ./client
      - run: docker run asheer/flying-fibo-test npm test -- --coverage
       
      - uses: actions/checkout@v2
      - name: Build Prod Version of all
      - run: docker build -t asheer/flyingfibo-client  ./client
      - run: docker build -t asheer/flyingfibo-worker  ./worker
      - run: docker build -t asheer/flyingfibo-nginx   ./nginx
      - run: docker build -t asheer/flyingfibo-server  ./server